import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    // Sidebar
    applyNow: "Apply Now",
    dashboard: "Dashboard",
    schemes: "Schemes",
    partners: "Partners",
    beneficiaries: "Beneficiaries",
    applications: "Applications",
    adminPortal: "Admin Portal",
    language: "Language",
    theme: "Theme",
    
    // Apply.jsx
    smartProfileTitle: "Smart Profile & Document Ingestion",
    smartProfileDesc: "Upload your documents and let AI extract your details automatically.",
    dragDropText: "Drag & drop Identity / Income documents",
    dragDropSub: "PDF, JPG, PNG · Aadhaar, PAN, Caste & Income Certificates",
    autoFillOcr: "Auto-Fill with AI OCR",
    scanningDocs: "Scanning documents…",
    profileFilled: "Profile auto-filled successfully!",
    fullName: "Full Name",
    age: "Age",
    gender: "Gender",
    category: "Category",
    annualIncome: "Annual Income (₹)",
    select: "Select…",
    male: "Male",
    female: "Female",
    transgender: "Transgender",
    other: "Other",
    general: "General",
    docChecklist: "Document Checklist",
    udyamCert: "Udyam Certificate",
    casteCert: "Caste Certificate",
    incomeCert: "Income Certificate",
    continueBtn: "Continue",
    backBtn: "Back",
    
    businessNeedsTitle: "Business Needs & Voice Input",
    businessNeedsDesc: "Tell us what you need. Speak in Hindi or English — we'll understand.",
    projectDomain: "Project Domain",
    selectDomain: "Select domain…",
    domainTailoring: "Tailoring",
    domainAgriculture: "Agriculture",
    domainAnimalHusbandry: "Animal Husbandry",
    domainEducation: "Education",
    domainHigherStudies: "Higher Studies",
    domainSmallManufacturing: "Small Manufacturing",
    domainFoodProcessing: "Food Processing",
    domainHandicrafts: "Handicrafts",
    domainTradeCommerce: "Trade & Commerce",
    domainTransport: "Transport",
    domainFisheries: "Fisheries",
    requestedAmount: "Requested Amount (₹)",
    tenure: "Preferred Loan Tenure (months)",
    voiceStop: "Stop",
    voiceBtn: "Voice",
    listening: "Listening… speak your amount in Hindi or English",
    heard: "Heard: ",
    analyseBtn: "Analyse Eligibility",
    reqAmountMsg: "Requested amount: ",
    
    analysisTitle: "AI Scheme Match & Gap Analysis",
    analysisDescBase: "Results for",
    applyingFor: "applying for",
    inDomain: "in",
    analysing: "Analysing eligibility…",
    retry: "Retry",
    notEligible: "Not Eligible",
    eligibleMsg: "Eligible for NSFDC financial assistance",
    matchedSchemeTitle: "Matched Scheme",
    maxLoan: "Max Loan",
    interestRate: "Interest Rate",
    moratoriumText: "Moratorium",
    subsidyText: "Subsidy",
    readinessScore: "Application Readiness",
    actionItemsTitle: "Action Items to improve your readiness score",
    allDocsOrder: "All documents are in order. Your application is ready to submit!",
    proceedBtn: "Proceed to Financial Calculator & Bank Router",
    proceedSub: "You will be shown EMI projections and nearest branch offices.",
    reAnalyseBtn: "Re-analyse",
    stepProfile: "Profile",
    stepBusiness: "Business",
    stepAnalysis: "Analysis",
    applyHeader: "Apply for NSFDC Loan Scheme",
    applyDesc: "Complete the 3-step wizard to receive a personalised scheme recommendation.",
    
    // Dashboard.jsx
    citizenDashboard: "Citizen Dashboard",
    dashboardDesc: "EMI projections and nearest branch routing for your NSFDC loan application.",
    downloadDossier: "Download Bank-Ready Dossier",
    moratoriumVisTitle: "Moratorium Visualizer",
    loanAmount: "Loan Amount",
    tenureSlider: "Tenure",
    moratoriumPeriod: "Moratorium Period",
    postMoratoriumEmi: "Post-Moratorium EMI",
    moratoriumPayment: "Moratorium Payment",
    totalInterest: "Total Interest",
    totalPayable: "Total Payable",
    monthRepaymentBreakdown: "Month-wise Repayment Breakdown",
    interestPaid: "Interest",
    principalPaid: "Principal",
    total: "Total",
    month: "Month",
    
    gisRouterTitle: "GIS Bank Router",
    gisRouterDesc: "Healthy branches within 100 km · NPA ≤ 8%",
    noHealthyBanks: "No healthy partners found within 100 km.",
    away: "away",
    
    // Admin.jsx
    adminHeader: "Bank Officer Admin Portal",
    adminDesc: "Manage applications, track readiness scores, and simulate NPA thresholds in real time.",
    submittedApps: "Submitted Applications",
    totalApps: "Total Applications",
    sanctionedApps: "Sanctioned",
    underReviewApps: "Under Review",
    totalRequested: "Total Requested",
    appId: "App ID",
    applicantName: "Applicant",
    domainCol: "Domain",
    amountCol: "Amount",
    schemeCol: "Scheme",
    scoreCol: "Score",
    submittedCol: "Submitted",
    statusCol: "Status",
    statusPending: "Pending",
    statusUnderReview: "Under Review",
    statusSanctioned: "Sanctioned",
    
    npaPanelTitle: "Fund Utilization / NPA Simulator",
    npaPanelDesc: "Slide to simulate NPA. Crossing 8% deactivates branch and triggers geospatial bypass.",
    branchBypassed: "branch bypassed",
    branchesBypassed: "branches bypassed",
    healthyLabel: "Healthy",
    thresholdLabel: "threshold",
    criticalLabel: "Critical",
    npaExceededTitle: "NPA Threshold Exceeded",
    npaExceededDesc1: "Geospatial router will now",
    npaExceededDescBold: "bypass this branch",
    npaExceededDesc2: "for new citizens. NPA must drop below 8% to restore routing eligibility.",
    branchActive: "✓ Branch active — eligible for citizen routing"
  },
  hi: {
    // Sidebar
    applyNow: "अभी आवेदन करें",
    dashboard: "डैशबोर्ड",
    schemes: "योजनाएं",
    partners: "भागीदार",
    beneficiaries: "लाभार्थी",
    applications: "आवेदन",
    adminPortal: "एडमिन पोर्टल",
    language: "भाषा",
    theme: "थीम",
    
    // Apply.jsx
    smartProfileTitle: "स्मार्ट प्रोफाइल और दस्तावेज़ अंतर्ग्रहण",
    smartProfileDesc: "अपने दस्तावेज़ अपलोड करें और AI को स्वचालित रूप से आपका विवरण निकालने दें।",
    dragDropText: "पहचान / आय दस्तावेज़ यहाँ खींचें और छोड़ें",
    dragDropSub: "PDF, JPG, PNG · आधार, पैन, जाति और आय प्रमाण पत्र",
    autoFillOcr: "AI OCR से स्वतः भरें",
    scanningDocs: "दस्तावेज़ स्कैन हो रहे हैं…",
    profileFilled: "प्रोफाइल सफलतापूर्वक भर गया!",
    fullName: "पूरा नाम",
    age: "आयु",
    gender: "लिंग",
    category: "श्रेणी",
    annualIncome: "वार्षिक आय (₹)",
    select: "चुनें…",
    male: "पुरुष",
    female: "महिला",
    transgender: "ट्रांसजेंडर",
    other: "अन्य",
    general: "सामान्य",
    docChecklist: "दस्तावेज़ चेकलिस्ट",
    udyamCert: "उद्यम प्रमाण पत्र",
    casteCert: "जाति प्रमाण पत्र",
    incomeCert: "आय प्रमाण पत्र",
    continueBtn: "आगे बढ़ें",
    backBtn: "पीछे",
    
    businessNeedsTitle: "व्यवसाय की आवश्यकताएं और वॉयस इनपुट",
    businessNeedsDesc: "हमें बताएं आपको क्या चाहिए। हिंदी या अंग्रेजी में बोलें — हम समझ जाएंगे।",
    projectDomain: "परियोजना क्षेत्र (डोमेन)",
    selectDomain: "क्षेत्र चुनें…",
    domainTailoring: "सिलाई",
    domainAgriculture: "कृषि",
    domainAnimalHusbandry: "पशुपालन",
    domainEducation: "शिक्षा",
    domainHigherStudies: "उच्च शिक्षा",
    domainSmallManufacturing: "लघु विनिर्माण",
    domainFoodProcessing: "खाद्य प्रसंस्करण",
    domainHandicrafts: "हस्तशिल्प",
    domainTradeCommerce: "व्यापार और वाणिज्य",
    domainTransport: "परिवहन",
    domainFisheries: "मत्स्य पालन",
    requestedAmount: "अनुरोधित राशि (₹)",
    tenure: "पसंदीदा ऋण अवधि (महीने)",
    voiceStop: "रोकें",
    voiceBtn: "बोलें",
    listening: "सुन रहे हैं… हिंदी या अंग्रेजी में अपनी राशि बोलें",
    heard: "सुना गया: ",
    analyseBtn: "पात्रता का विश्लेषण करें",
    reqAmountMsg: "अनुरोधित राशि: ",
    
    analysisTitle: "AI योजना मिलान और गैप विश्लेषण",
    analysisDescBase: "के लिए परिणाम",
    applyingFor: "आवेदन राशि:",
    inDomain: "क्षेत्र में",
    analysing: "पात्रता का विश्लेषण हो रहा है…",
    retry: "पुनः प्रयास करें",
    notEligible: "पात्र नहीं",
    eligibleMsg: "NSFDC वित्तीय सहायता के लिए पात्र",
    matchedSchemeTitle: "मिलान की गई योजना",
    maxLoan: "अधिकतम ऋण",
    interestRate: "ब्याज दर",
    moratoriumText: "मोरेटोरियम (छूट अवधि)",
    subsidyText: "सब्सिडी",
    readinessScore: "आवेदन तत्परता (Readiness)",
    actionItemsTitle: "तत्परता स्कोर सुधारने के लिए आवश्यक कदम",
    allDocsOrder: "सभी दस्तावेज़ सही हैं। आपका आवेदन प्रस्तुत करने के लिए तैयार है!",
    proceedBtn: "वित्तीय कैलकुलेटर और बैंक राउटर पर जाएं",
    proceedSub: "आपको EMI अनुमान और निकटतम शाखा कार्यालय दिखाए जाएंगे।",
    reAnalyseBtn: "पुनः विश्लेषण करें",
    stepProfile: "प्रोफाइल",
    stepBusiness: "व्यवसाय",
    stepAnalysis: "विश्लेषण",
    applyHeader: "NSFDC ऋण योजना के लिए आवेदन करें",
    applyDesc: "व्यक्तिगत योजना अनुशंसा प्राप्त करने के लिए 3-चरणीय विज़ार्ड पूरा करें।",
    
    // Dashboard.jsx
    citizenDashboard: "नागरिक डैशबोर्ड",
    dashboardDesc: "आपके NSFDC ऋण आवेदन के लिए EMI अनुमान और निकटतम शाखा रूटिंग।",
    downloadDossier: "बैंक-रेडी डॉज़ियर डाउनलोड करें",
    moratoriumVisTitle: "मोरेटोरियम विज़ुअलाइज़र",
    loanAmount: "ऋण राशि",
    tenureSlider: "अवधि",
    moratoriumPeriod: "मोरेटोरियम अवधि",
    postMoratoriumEmi: "मोरेटोरियम के बाद की EMI",
    moratoriumPayment: "मोरेटोरियम भुगतान",
    totalInterest: "कुल ब्याज",
    totalPayable: "कुल देय राशि",
    monthRepaymentBreakdown: "महीनेवार पुनर्भुगतान विवरण",
    interestPaid: "ब्याज",
    principalPaid: "मूलधन",
    total: "कुल",
    month: "महीना",
    
    gisRouterTitle: "GIS बैंक राउटर",
    gisRouterDesc: "100 किमी के भीतर स्वस्थ शाखाएं · NPA ≤ 8%",
    noHealthyBanks: "100 किमी के भीतर कोई स्वस्थ भागीदार नहीं मिला।",
    away: "दूर",
    
    // Admin.jsx
    adminHeader: "बैंक अधिकारी एडमिन पोर्टल",
    adminDesc: "आवेदनों का प्रबंधन करें, तत्परता स्कोर ट्रैक करें, और वास्तविक समय में NPA थ्रेशोल्ड का अनुकरण करें।",
    submittedApps: "प्रस्तुत किए गए आवेदन",
    totalApps: "कुल आवेदन",
    sanctionedApps: "मंजूर",
    underReviewApps: "समीक्षाधीन",
    totalRequested: "कुल अनुरोध",
    appId: "आवेदन ID",
    applicantName: "आवेदक",
    domainCol: "डोमेन",
    amountCol: "राशि",
    schemeCol: "योजना",
    scoreCol: "स्कोर",
    submittedCol: "प्रस्तुत",
    statusCol: "स्थिति",
    statusPending: "लंबित",
    statusUnderReview: "समीक्षाधीन",
    statusSanctioned: "मंजूर",
    
    npaPanelTitle: "फंड उपयोग / NPA सिमुलेटर",
    npaPanelDesc: "NPA का अनुकरण करने के लिए स्लाइड करें। 8% पार करने पर शाखा निष्क्रिय हो जाती है और जियोस्पेशियल बायपास ट्रिगर होता है।",
    branchBypassed: "शाखा बायपास की गई",
    branchesBypassed: "शाखाएं बायपास की गईं",
    healthyLabel: "स्वस्थ",
    thresholdLabel: "सीमा (थ्रेशोल्ड)",
    criticalLabel: "गंभीर (क्रिटिकल)",
    npaExceededTitle: "NPA सीमा पार हो गई",
    npaExceededDesc1: "जियोस्पेशियल राउटर अब नए नागरिकों के लिए",
    npaExceededDescBold: "इस शाखा को बायपास",
    npaExceededDesc2: "करेगा। रूटिंग पात्रता बहाल करने के लिए NPA को 8% से नीचे आना होगा।",
    branchActive: "✓ शाखा सक्रिय है — नागरिक रूटिंग के लिए पात्र"
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || key
  }

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en')
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
